server {
    listen 80;
    server_name _;

    client_max_body_size 10m;

    location = /health {
        proxy_pass http://mp_seller_bot_app:8000/health;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /webhook {
        proxy_pass http://mp_seller_bot_app:8000/webhook;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_connect_timeout 10s;
        proxy_send_timeout 30s;
        proxy_read_timeout 30s;
    }

    location / {
        return 404;
    }
}
